endorsement = #6.55799([
    e-type,
    [
        scope: scope-data,
        evidence: evidence-data,
        endorser: endorser-data,
        signature: signature-data
    ]
])
e-type = uint .size(2)
scope-data = [
    vnb: time,
    vna: time,
]
evidence-data = data
endorser-data = data
signature-data = data
data = [any] / {* label => values} / bstr / any
label = int / tstr
values = any